### ISSUE TITLE
Using a UL instead of OL for the Instructions List

### ISSUE THREAD

**Issue by w33zy** [dasmaeh/recipepress-reloaded#13]
Is there any technical reason why you choose an unordered list for displaying the instructions list? I am considering switching to an ordered list in my fork but I want make sure it doesn't cause any unforeseen problems.

**Comment by jckoester** [comment]
If I remember it right there was an issue with ordered lists and instruction group titles. This should be fixed however,
I have to admit that an ordered list does make sense for instructions

**Comment by w33zy** [comment]
I tried it and I noticed a group becomes the child of the list item above it or something like that. It's weird.

Today I took time to re-do the print function using a better jQuery print library and 'wp_localize_script'. Can you take a look at and tell me if you'll be interested in accepting a pull request for this improvement.

https://github.com/w33zy/recipepress-reloaded/commit/9e84e3ca035457be2f4efe95c04d79e25212034d

**Comment by jckoester** [comment]
I've taken care of the instruction list in e213853.

I'll look into your suggestion on the weekend. But in general I'm always interested in improvements.

**Comment by w33zy** [comment]
Thanks!
