### ISSUE TITLE
Universal print option or per template option.

### ISSUE THREAD

**Issue by w33zy** [dasmaeh/recipepress-reloaded#17]
What are your thoughts on a universal print button option rather than have it as a per template option. I creating a PR for an update print function but I considering enqueuing the JS file in ````class-rpr-public.php```` rather than the default per theme ````functions.php````.

Is there any particular reason why you chose the per template route?

**Comment by jckoester** [comment]
The print class is some legacy code from an old release. I don't really remember why I put it to the templates. It's probably a lot older than the template feature itself.
I currently don't see any reason to keep it there.
I've always considered a blog wide print button solution as provided by many plugins specialized in that to be better than a print button working only on recipes. But as the demand seems to be there, why not include one?

**Comment by w33zy** [comment]
Submitted PR #24

**Comment by w33zy** [comment]
Closed with PR #24
