### ISSUE TITLE
Dashboard notice not dismissable

### ISSUE THREAD

**Issue by jevgen** [dasmaeh/recipepress-reloaded#21]
The initial dashboard notice cannot be dismissed. (At least on WP Engine hosting).  
<img width="1163" alt="screen shot 2017-01-30 at 12 43 57" src="https://cloud.githubusercontent.com/assets/255431/22418479/4958c458-e6ea-11e6-9492-ba1472704ee9.png">

**Comment by jckoester** [comment]
Resolved in release 0.9.0
