### ISSUE TITLE
The "Screen Options" content is hidden when RPR is active.

### ISSUE THREAD

**Issue by w33zy** [dasmaeh/recipepress-reloaded#35]
I saw the issue on the WP forum and notice the 'hidden' CSS rule on L1 of ````rpr-admin.css````. This fix I came up with is to change class selector to ````.post-type-rpr_recipe .hidden```` and/or use ````get_current_screen()->post_type == 'rpr_recipe'```` to enqueue the admin CSS file only on RPR admin pages.

I didn't create a PR because I saw that you probably created the new branch to fix this issue.

**Comment by jckoester** [comment]
That's exactly the problem. To avoid any side effects I'd rather change the selector to `.rpr-hidden`. The fix will be available soon.
