### ISSUE TITLE
Custom taxonomy data missing after update.

### ISSUE THREAD

**Issue by w33zy** [dasmaeh/recipepress-reloaded#43]
I just switch to the '0.9.2' version of the plugin available on wordpress.org. After switching, I have noticed the my previous enter taxonomies for course, season, cuisine is not longer showing up on the backend or frontend.

Can you point me to the change that was made that would have affected old taxonomies?

**Comment by jckoester** [comment]
This should not be happening! Old taxonomies should never be deleted.
Which version have you been using before the upgrade?

**Comment by w33zy** [comment]
The old taxonomies are there, it seems that they are called `rpr_season` and `rpr_cuisine` in the DB while the plugin is looking for `season` and `cuisine`.

The plugin was one `v0.8.3` but it was heavily customized by me, for styling the recipe template.

**Comment by jckoester** [comment]
The last update really changing the database was from 0.7.x to 0.8.x, so this can't be the problem. Taxonomies should be saved in the database in `rpr_options`. This is a serialized options object. Your taxonomies should be saved in `[tax_custom] `.
You could also try to manually add the taxonomies in the backend using `rpr_season` and `rpr_cuisine` as slug.
I'll try to have a closer look at this tomorrow.

**Comment by w33zy** [comment]
Ignore this, I'll work backward from a site backup and figure out what's happening, when I update.
I will report back to you on what exactly happened
