### ISSUE TITLE
'kcal' vs 'cal' for the calorie nutrition information

### ISSUE THREAD

**Issue by w33zy** [dasmaeh/recipepress-reloaded#47]
I just had a client point out to me that RPR is asking for the calorie information in kilocalories but some of her recipes such as soups have small calories values such as 230 calories.

When trying to enter 230 calories as 0.23 kcal, the form validation prevents entering values below 0

So I am thinking of adjusting the input field to accept and use the calories without the kilo unit

**Comment by jckoester** [comment]
I would agree to change the validation on the field to accept values between 0 and 1 (Values below 0 would be great, meaning that eating this dish would help you losing weight by consuming calories :) ).
It would also be useful to change the template tag to print out 230 cal insetad of 0.23 kcal.
As the value is stored in the database as kcal I would not really like to change the unit in general, as a migration script then would have to convert all the stored values from kcal to cal.

**Comment by w33zy** [comment]
As it is right now, something is not right with the values the site is displaying. I think the values the plugin is storing may be the actual calorie count with the `kilo` prefix. I say this because when I run a ingredient list for a soup through the nutrition calculator at https://www.edamam.com/website/wizard.jsp?ver=wizard-basic the values are return as calories but the plugin displays it as `kcal`

So most likely only the label needs to be changed

Here is an example of a soup recipe:
https://healthiersteps.com/recipe/jamaican-pumpkin-soup-pureed/

**Comment by jckoester** [comment]
No, the values are displaying correctly. I've just checked.
Let's take for example 100mL of apple juice with contains an energy of 46kcal  or 192 kJ. It is saved and displayed as it should be.
The problem might be however that quite a lot of people drop the 'k' in 'kcal' as in common language people are usually talking about 'calories' when referencing the energy of a kilocalory.
This also applies to the site you've referenced. They are talking abot 'calories' in the sense of 'kilocalories'. (Btw the famous 200 calories diet is indeed a 2000kcal (8420kJ) diet!)
