### ISSUE TITLE
Shortcodes should be stripped for recipe description JSON data

### ISSUE THREAD

**Issue by w33zy** [dasmaeh/recipepress-reloaded#48]
I have just notice that the schema data was invalid from a couple recipes on my site. On closer inspection I could see that div tags where present in the description which broken the markup. The div where coming from a shortcode I used to insert FB videos.

I fixed this issue by using the `strip_shortcodes` function on L414 of the template tags file

**Comment by jckoester** [comment]
Thanks for the hint. This is fixed in the modularized version.
