### ISSUE TITLE
The new pluralization feature also affects existing manually pluralized ingredients

### ISSUE THREAD

**Issue by w33zy** [dasmaeh/recipepress-reloaded#7]
The new pluralization feature will add an extra 's' the existing ingredients that were previously manually pluralized before this update.b So if before this update I entered 'potatoes', after updating this entry will now display as 'potatoess'. 

This feature ought to be an option that defaults to off.

**Comment by jckoester** [comment]
That's true. Never thought about this while developing the feature.

**Comment by w33zy** [comment]
I was thinking of adding it as a option for the ingredients section. First I'll have to take a look at how you create option in the admin area.

However when I think about it, this feature should be left out because pluralization of words is tricky in English or any other language. How do you approach edge cases like 'fish', 'goose', 'leaf' or 'loaf'?

Leave this feature out, the recipe writers should be doing this.

**Comment by jckoester** [comment]
I'll add the option to the ingredients options pane, that's not much work.

The edge cases are already taken care of, each ingredient has it's own plural field in the term definition. Default pluralization is only used if this field is empty. In languages like German pluralization rules don't really work. In German around 50% of all ingredients have an irregular plural!
However I think this feature to be essential. If you reference recipes by ingredient using no pluralization get get confusing. You will end up with recipes using (1) tomato and recipes using tomatoes. So you have two terms appearing where one would be appropriate from a taxonomy point of view.

**Comment by jckoester** [comment]
Maybe I should provide a migration function to join manually created singular and plural versions of an ingredient ...

**Comment by w33zy** [comment]
I understand the need for this option now because often I have to go through the ingredients taxonomy list to remove the duplicates as you mention. And I am just noticing the "Plural name" option in the term definition section. I'll close this issue.


I want you verify something for me...
Change your Ingredients link target option to "Custom link if available, otherwise archive page". Then check the link targets and see where they point. On my installation, they point to the full recipe URL.

**Comment by jckoester** [comment]
Confirmed and fixed.

**Comment by w33zy** [comment]
I applied the fix and the links now work as they should.
