### ISSUE TITLE
recipepress-reloaded.pot contains German translations

### ISSUE THREAD

**Issue by henriksommerfeld** [dasmaeh/recipepress-reloaded#9]
When I want to create a new translation I want to start blank. When translating the plugin for your own needs (e.g. through _Loco Translate_) you might not want to translate everything, such as texts in the admin interface. As it is now you have to replace all the texts, otherwise they end up in German. A translation tool will also indicate that 100% of the texts are translated, even before you start to translate.

Suggestion: Leave **recipepress-reloaded.pot** untranslated.

**Comment by jckoester** [comment]
That's true and my mistake. Will fix this soon in 0.8.1.
However please use [translate.wordpress.org](https://translate.wordpress.org/projects/wp-plugins/recipepress-reloaded) to translate the plugin.
By the way: poedit doesn't show this behaviour.
